### ISSUE TITLE
Equalent go benchmark

### ISSUE THREAD

**Issue by heppu** [squeaky-pl/japronto#11]
The header setting thing only slows hello function and actually does nothing. Also the is no need to declare those temporary text and status variables on every request.

**Comment by squeaky-pl** [comment]
I updated the article in two plaes with the following text:

> As user @heppu points out Go’s stdlib HTTP server can be 12% faster than the graph shows when written more carefully. Also there is the awesome fasthttp server for Go that apparently is only 18% slower than Japronto in this particular benchmark. Awesome! For details see https://github.com/squeaky-pl/japronto/pull/12 and https://github.com/squeaky-pl/japronto/pull/14
