### ISSUE TITLE
Is there a way I can execute certain code upon webserver  start? 

### ISSUE THREAD

**Issue by fourjr** [squeaky-pl/japronto#110]
Title ^^

**Comment by imgurbot12** [comment]
@fourjr You can wrap the application to execute code on startup.

Here is an example:

`
from japronto import Application

class App(Application):

	def run(self, *args, **kwargs):
		print("Code has been executed")
		Application.run(self, *args, **kwargs)


def hello(request):
    return request.Response(text='Hello world!')


app = App()
app.router.add_route('/', hello)
app.run(debug=True)
`

Hope that helps!

**Comment by fourjr** [comment]
Oh ok thanks!
