### ISSUE TITLE
What's the catch?

### ISSUE THREAD

**Issue by brandonros** [squeaky-pl/japronto#142]
Is this faster than all C/Java/Rust implementations out there?

**Comment by squeaky-pl** [comment]
Your experience will vary depending on what kind of logic you put there in Python. There definitely exist faster implementations for those 3 languages you mentioned.

You can look here for some 3rd party benchmarks against other languages:

https://github.com/the-benchmarker/web-frameworks
and https://www.techempower.com/benchmarks/#section=data-r17&hw=ph&test=plaintext
