### ISSUE TITLE
Is it recommended for use in the production environment?

### ISSUE THREAD

**Issue by guolimin1995** [squeaky-pl/japronto#159]
Is there anybody use japronto in the production environment?  
Will there be many bugs?

**Comment by mononobi** [comment]
it's very amazing but there is not any actual release available. the pypi package is also very outdated.
if you want to use it in production you have to heavily unit-test it. and prepare yourself for debugging and also extending it for your use case. and another major issue with all async frameworks is that there is not any stable async ORM available. there is some like GINO or DATABASES but all of them are quit new in comparison to sqlalchemy. so there would be a lot of work for you to do if you want to use it.

**Comment by guolimin1995** [comment]
> it's very amazing but there is not any actual release available. the pypi package is also very outdated.
> if you want to use it in production you have to heavily unit-test it. and prepare yourself for debugging and also extending it for your use case. another major issue with all async frameworks is that there is not any stable async ORM available. there are some like GINO or DATABASES but all of them are quite new and immature in comparison to sqlalchemy. so there would be a lot of work for you to do if you want to use it.

What you said is very helpful. Thanks！

**Comment by mononobi** [comment]
> > it's very amazing but there is not any actual release available. the pypi package is also very outdated.
> > if you want to use it in production you have to heavily unit-test it. and prepare yourself for debugging and also extending it for your use case. another major issue with all async frameworks is that there is not any stable async ORM available. there are some like GINO or DATABASES but all of them are quite new and immature in comparison to sqlalchemy. so there would be a lot of work for you to do if you want to use it.
> 
> What you said is very helpful. Thanks！

You're welcome.

**Comment by lavdnone** [comment]
Yes. No bugs that might be a concern
