### ISSUE TITLE
can't install japronto

### ISSUE THREAD

**Issue by shan-guo** [squeaky-pl/japronto#163]
### Hi, I can't wait  to attempt this awesome web framework, but I can't install it

`(venv) ➜  japronto_demo python -V`
`Python 3.7.1`
`(venv) ➜  japronto_demo pip -V`
`pip 19.2.2 from /Users/shanguo/code/python/japronto_demo/venv/lib/python3.7/site-packages/pip (python 3.7)`

**pip install japronto**

Collecting japronto
  ERROR: Could not find a version that satisfies the requirement japronto (from versions: none)
ERROR: No matching distribution found for japronto

**Comment by Agent-Hellboy** [comment]
why there is no comment on this issue. 
> Hi, I can't wait to attempt this awesome web framework, but I can't install it

Take a look at [this.](https://github.com/squeaky-pl/japronto/issues/167#issuecomment-560204336)

**Comment by shan-guo** [comment]
> why there is no comment on this issue.
> 
> > Hi, I can't wait to attempt this awesome web framework, but I can't install it
> 
> Take a look at [this.](https://github.com/squeaky-pl/japronto/issues/167#issuecomment-560204336)


Thanks😊,  Now I'm installed success by souce code

Steps:

1.`git clone https://github.com/squeaky-pl/japronto.git`
2.`cd japronto`
3.`virtualenv venv -p=python3.7`
4.`source venv/bin/activate`
5.`python setup.py install`

Output: 
.................
`Finished processing dependencies for japronto==0.1.2`

**Comment by wait3** [comment]
For whoever come across this issue, you could just run:

`pip install git+https://github.com/squeaky-pl/japronto.git`
