### ISSUE TITLE
Unhandled exception in event loop

### ISSUE THREAD

**Issue by hanymorcos** [squeaky-pl/japronto#164]
Is that on the list of issues?

wrk -t12 -c400 -d30s

versions/3.6.9/lib/python3.6/site-packages/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
ValueError: View did not return Response instance
Unhandled exception in event loop

**Comment by eirnym** [comment]
You should change return type of your function to return a Response instance instead of anything else.

**Comment by hanymorcos** [comment]
import random
from japronto import Application




def generaterandom(request):
     number = random.randint(0, 100)
     result = {'lowerLimit': 0, 'higherLimit': 100, 'number': number}
     request.Response(json=result)

app = Application()
r = app.router
r.add_route('/number', generaterandom, method='GET')
app.run()

Is "json" not a valid return type?

**Comment by hanymorcos** [comment]
I will try text.
