### ISSUE TITLE
How to match all current items in a certain directory

### ISSUE THREAD

**Issue by Fgaoxing** [squeaky-pl/japronto#193]
@kwadrat Is there any way? I want to match all the content under a certain path
有什么办法吗？我希望匹配某一个路径下的所以内容

**Comment by Fgaoxing** [comment]
Sorry, I didn't read the document carefully

**Comment by Fgaoxing** [comment]
@squeaky-pl When I use "router. add_route ("/gh/{path} ", github. getFile)", I cannot match correctly

**Comment by Fgaoxing** [comment]
I am not matching a separate directory, but all the directories below

**Comment by Fgaoxing** [comment]
Additionally, when I call any function or class other than a custom one of 'request', calling 'request. Response' will result in 'SystemError: error return without exception set'

**Comment by Fgaoxing** [comment]
@squeaky-pl

**Comment by Ronnie420b** [comment]
Javac
