### ISSUE TITLE
Submit the framework to Techempower benchmarks

### ISSUE THREAD

**Issue by santagada** [squeaky-pl/japronto#24]
To be able to have some comparison with other frameworks it would be great if someone implements all the techempower benchmarks and submit a PR for them so that it will be part of the next round of benchmarks.

I might be able to do this in the future, but if anyone wants to do it please go ahead, just leave a comment here :)

**Comment by GMLudo** [comment]
It should be awesome, I've the sanic integration in the pipe for framework benchmarks, but I'might very busy.

If some other people could contribute, it might be awesome.

**Comment by squeaky-pl** [comment]
Somebody did that already at least for json and plaintext: https://www.techempower.com/benchmarks/#section=data-r16&hw=ph&test=json
