### ISSUE TITLE
No module named '/hello' on Python search path.

### ISSUE THREAD

**Issue by techesuraj** [squeaky-pl/japronto#25]
Hi, I am new to all this docker. After following all the instructions when I try to run this command in terminal:
docker run -P -v hello.py:/hello.py japronto/japronto /hello.py

It appears to have following error message
No module named '/hello' on Python search path 

Can you please help me with this

**Comment by squeaky-pl** [comment]
Sorry for that. This is docs issue, forgot to update that. The correct command is:

`docker run --rm -p 8080:8080 -v `pwd`/hello.py:/hello.py japronto/japronto --script /hello.py`

**Comment by squeaky-pl** [comment]
Fixed in ed1ec27
