### ISSUE TITLE
Can I allow CORS?

### ISSUE THREAD

**Issue by HueyPark** [squeaky-pl/japronto#31]
If not, where can I add it?

**Comment by aphillipo** [comment]
CORS is just a header or a meta tag.  It's relatively simple to add headers to the response object I imagine.

**Comment by aphillipo** [comment]
Okay so when returning a request.Response(headers={'Access-Control-Allow-Origin': 'some uri'}) should be a starting point for you...

**Comment by HueyPark** [comment]
Thank you
