### ISSUE TITLE
Templating example?

### ISSUE THREAD

**Issue by nicholastulach** [squeaky-pl/japronto#38]
I apologize if this is too noobie of a question, but could someone write an example of how to use templating with Japronto? I'm used to Flask with built-in templating support and I don't know how to get started without it.

**Comment by Superman132** [comment]
This would be possible if Japronto had a html option in the response object. Am I missing something? or is there a workaround to achieve html as response

**Comment by squeaky-pl** [comment]
@Superman132 you can do `request.Response(text='<h5>Hello</h5>', mime_type='text/html')`

**Comment by squeaky-pl** [comment]
This needs a recipe, meaning that somebody should write a piece of code that demonstrates how to use templating with Japronto. Fairly easy for experienced people and tremendously useful for newcomers.

I will accept a pull request.

**Comment by fer1934** [comment]
f(e)r1934

**Comment by jacobbridges** [comment]
@squeaky-pl, I'll submit a PR for this within the next hour.

**Comment by squeaky-pl** [comment]
Many thanks @jacobbridges, @nicholastulach there is now an example in the examples folder.

**Comment by nicholastulach** [comment]
Thank you from me and all the other noobs!
