### ISSUE TITLE
css and js 

### ISSUE THREAD

**Issue by jersobh** [squeaky-pl/japronto#43]
Hi there,

I'm trying to run the html example, but js and css files get error 404

**Comment by squeaky-pl** [comment]
Hard to comment on the thing without a code example, make a minimal example that fails for you and explains what you wanna do and I am sure somebody will help you.

**Comment by jersobh** [comment]
I was running your project's example. Then I've added a js tag on the header of the html file, but it gets 404 error, on any file. I know this must be something stupid.. it's just because i'm new to python. In php it could be solved by a "__FILE__" or "__DIR__" maybe.

**Comment by squeaky-pl** [comment]
If you are new to Python I would suggest you try some framework that provides static file serving capabilities like Sanic, Falcon or Flask. Japronto is targeted for particular use cases of speed enthusiasts. It is not yet a general purpose web framework I hope it becomes one day.

**Comment by jersobh** [comment]
I see. I've actually started writting this -> https://github.com/jersobh/pydge
Solved the problem creating a route for the static files :+1: 

Thanks

**Comment by pingf** [comment]
I'm trying to build a framework upon this, now I just simple use the code like this
```python
from japronto import Application


async def hello(request):
    path = request.match_dict['static_file'].strip('/')

    with open(path) as html_file:
        return request.Response(text=html_file.read(), mime_type='text/html')


app = Application()

app.router.add_route('/static/{static_file}', hello)

app.run(debug=True, port=8765)
```

**Comment by Snuggert** [comment]
Because my static files were in a multi-tiered file tree i hacked something together, i'm not proud....

```
from japronto import Application

def content(request):
    with open(request.path[1:], 'rb') as static_file:
        return request.Response(body=static_file.read())

app = Application()

app.router.add_route('/static/{1}', static)
app.router.add_route('/static/{1}/{2}', static)
app.router.add_route('/static/{1}/{2}/{3}', static)

app.run(debug=True)
```

Performance for a 5kB file.
```
wrk -t 1 -c 100 -d 1m http://localhost:8080/static/1/2/3.file
Running 1m test @ http://localhost:8080/static/1/2/3.file
  1 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     6.32ms    2.95ms  28.84ms   77.73%
    Req/Sec    16.04k     3.97k   22.81k    54.50%
  958039 requests in 1.00m, 4.53GB read
Requests/sec:  15955.85
Transfer/sec:     77.18MB
```
