### ISSUE TITLE
No way to change/specify the Server Headers

### ISSUE THREAD

**Issue by imgurbot12** [squeaky-pl/japronto#57]
The base server headers list:
<ul>
  <li>Status_Code</li>
  <li>Content Length</li>
  <li>Content Type</li>
</ul>

But I would like to be able to provide:
<ul>
  <li>Date</li>
  <li>Server Type</li>
  <li>Last Modified</li>
  <li>Accepted Ranges</li>
</ul>

**I mainly want to disguise Japronto as another web-service...**

**Comment by aphillipo** [comment]
Hmmmm.... 

https://github.com/squeaky-pl/japronto/blob/master/tutorial/5_response.md

```python
  # And of course you can provide custom `headers`.
  def headers(request):
      return request.Response(
          text='headers',
          headers={'X-Header': 'Value',
                   'Refresh': '5; url=https://xkcd.com/353/'})
```

**Comment by imgurbot12** [comment]
@aphillipo  Wow. Guess I overlooked that in the examples. I started searching through source code to try and find this. Thanks.
