### ISSUE TITLE
local benchmark way slower?

### ISSUE THREAD

**Issue by kootenpv** [squeaky-pl/japronto#63]
pascal@MBP:~/ $ wrk -c 100 -t 1 -d 10 http://localhost:8080/

Running 10s test @ http://localhost:8080/
  1 threads and 100 connections
   Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   710.49us  142.66us   1.63ms   73.21%
    Req/Sec   134.71k     7.86k  141.24k    92.31%
  348236 requests in 2.60s, 30.55MB read
Requests/sec: 133848.43
Transfer/sec:     11.74MB

What is the explanation for this?

**Comment by squeaky-pl** [comment]
Benchmarks are useless without specifying the actual platform. Also you didn't use pipelining.
See https://github.com/squeaky-pl/japronto/issues/8 and https://github.com/squeaky-pl/japronto/issues/21 and

**Comment by kootenpv** [comment]
In other issues pipelining is only shown to be a little bit of a difference, and in another it is mentioned that this won't happen in browsers.

The platform is OSX on a MBP 2014, using python 3.5 and the latest version of japronto on pip.

Regardless, I'd say rather than closing the issue it'd be interesting to find out why I have 10x slower than a benchmark...
