### ISSUE TITLE
how can I use redirect in a response?

### ISSUE THREAD

**Issue by SumonMSelim** [squeaky-pl/japronto#65]
I want to redirect my response to an url rather than returning something. At the moment, I am doing it this way:

`return request.Response(headers={'Refresh': '0; url=https://github.com/squeaky-pl/japronto'})`

Is there any better way?

**Comment by squeaky-pl** [comment]
Just use standard HTTP way `Location` header and 30x responses: https://en.wikipedia.org/wiki/URL_redirection#HTTP_status_codes_3xx

**Comment by vadim-shadrin** [comment]
return request.Response(headers={'Location': '/login'}, code=302)
return request.Response(headers={'Location': '/'}, code=302)
