### ISSUE TITLE
Bug found when 'from japronto import Application'

### ISSUE THREAD

**Issue by ghosttk** [squeaky-pl/japronto#71]
In example/8_html/html.py
With the name "html.py",running this script results "ImportError: cannot import name 'Application'".
When change it's name from "html.py" to "htm.py" or anything else,script runs with no errors.

**Comment by alexandremasbr** [comment]
It should be a namespace problem. html probably is used in another module.

Em 27/04/2017 04:59, "ghosttk" <notifications@github.com> escreveu:

**Comment by ghosttk** [comment]
This makes sence,I found a python3 buildin module named 'html'.

**Comment by squeaky-pl** [comment]
Fixed as of 866bca3d910f8aee788f6861ec3770b4f09c1ae9

**Comment by WesleyBatista** [comment]
This issue happened with me too. The problem was that my script file was named as `japronto.py`. Renamed to a different name than the package and it worked.
