### ISSUE TITLE
logging support

### ISSUE THREAD

**Issue by gsakkis** [squeaky-pl/japronto#72]
First off kudos for the awesome work, great to see a high performance Python web framework!

I've noticed `japronto.Application` contains several [print statements](https://github.com/squeaky-pl/japronto/blob/master/src/japronto/app/__init__.py). It would be nice to replace them with logging calls so it's easier for apps to suppress output or more generally customize how are things being logged.

**Comment by hieu-n** [comment]
When I run japronto on my local machine, it outputs the urls that are being accessed e.g.:
```
127.0.0.1 GET /
127.0.0.1 GET /favicon.ico
```

However, when I run japronto in a docker container, I don't see these outputs. So I'm trying to figure out what code is responsible for these outputs. Please give me some hints.
