### ISSUE TITLE
Fix Golang code for Benchmark

### ISSUE THREAD

**Issue by rebootcode** [squeaky-pl/japronto#83]
Please fix the golang code for benchmark purpose - 

```
package main
import (
    "net/http"
)

func main() {
	http.HandleFunc("/", func hello(w http.ResponseWriter, r *http.Request) {
	    w.Write([]byte("Hello world!"))
        })
	http.ListenAndServe("0.0.0.0:8080", nil)
}
```

Use Above code and please test the bechmark of `golang` with `japronto`. Same goes with `fasthttp`

**Comment by squeaky-pl** [comment]
This was discussed many times. The benchmark purpose is comparing single-core performance. Anyway if you are looking for multi core numbers these were done: https://github.com/squeaky-pl/japronto/pull/14

**Comment by rebootcode** [comment]
@squeaky-pl - Are you serious ? Above code is single-core performance. But using unwated `if` code unwanted variable creation.

```
package main
import "net/http"

/*
** Below Code is not required .
var (
	helloResp    = []byte("Hello world!")
	notFoundResp = []byte("Not Found")
)
*/
func hello(w http.ResponseWriter, r *http.Request) {

/*
* ===   Seriously ???     Why did you forget more of "if" with    if r.URL.Path != "404" , "500", "401" and all other variant too  ====   This is un wanted call below.

	if r.URL.Path != "/" {
		w.WriteHeader(http.StatusNotFound)
		w.Write(notFoundResp)
		return
	}

*/

// You can simply call []byte("Hello World") here without any variable creation. 

//	w.Write(helloResp)

w.Write([]byte("Hello World"))
}

func main() {
        // You can call `func` right here inside `HandleFunc` but many people tend to use othr way. 
       // So, i will leave that as it is.
	http.HandleFunc("/", hello)
	http.ListenAndServe("0.0.0.0:8080", nil)
}
```

Above is your code . Can you see difference ?? Doing same work running on "single-core performance" but code and performance will vary a lot.

Especially when getting nodejs result as closer to golang itself looks funny.

**Comment by squeaky-pl** [comment]
Please compare this with other benchmarks, they all have the same logic for 404. Go won't do this by default so it needs to be added. Otherwise it is unfair.

**Comment by squeaky-pl** [comment]
The particular global variable change was done here: https://github.com/squeaky-pl/japronto/pull/12/files and measured 18% speed up for Go.
