### ISSUE TITLE
Need Sample for Session Management !

### ISSUE THREAD

**Issue by tejastank** [squeaky-pl/japronto#93]
# Thanks for your great effort for japronto,

Looking to know how session management we easily able to achive ?

Or for mement cas you suggest best python libraries which we can utilize for session managmen with Japronto

**Comment by tejastank** [comment]
@squeaky-pl Please keep upgrade your framework, we love to utilize it.

**Comment by imgurbot12** [comment]
@tejastank While I'm not sure if japronto is planning on implementing this or not, its unlikley this will happen for a while.

Why not try implementing this yourself? If your trying to mimic something like PHP's SESSID, then you just need to add extra code or wrap your functions to include checks for session cookies with some sort of persistent data source like a database.

**Comment by tejastank** [comment]
@imgurbot12 within japronto, make some standarded code. Also Believe better if added with c extension based speedup based session fatures... library creator might had idea.

Yes. for my personal I had already utilzied different  way...

**Comment by tejastank** [comment]
BASIC OF WEB FRAMEWORK YET DATE NOT DOCUMENT OR UPDATED.
